System.config({
  defaultJSExtensions: true,
  transpiler: "babel",
  babelOptions: {
    "optional": [
      "es7.decorators",
      "es7.classProperties"
    ]
  },
  paths: {
    "*": "dist/*",
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*"
  },
  map: {
    "aurelia-animator-css": "npm:aurelia-animator-css@1.0.0-beta.1.1.2",
    "aurelia-bootstrapper": "npm:aurelia-bootstrapper@1.0.0-beta.1.1.4",
    "aurelia-fetch-client": "npm:aurelia-fetch-client@1.0.0-beta.1.1.1",
    "aurelia-framework": "npm:aurelia-framework@1.0.0-beta.1.1.4",
    "aurelia-history-browser": "npm:aurelia-history-browser@1.0.0-beta.1.1.4",
    "aurelia-loader-default": "npm:aurelia-loader-default@1.0.0-beta.1.1.3",
    "aurelia-logging-console": "npm:aurelia-logging-console@1.0.0-beta.1.1.4",
    "aurelia-pal-browser": "npm:aurelia-pal-browser@1.0.0-beta.1.1.4",
    "aurelia-polyfills": "npm:aurelia-polyfills@1.0.0-beta.1.0.0",
    "aurelia-router": "npm:aurelia-router@1.0.0-beta.1.1.2",
    "aurelia-templating-binding": "npm:aurelia-templating-binding@1.0.0-beta.1.1.2",
    "aurelia-templating-resources": "npm:aurelia-templating-resources@1.0.0-beta.1.1.2",
    "aurelia-templating-router": "npm:aurelia-templating-router@1.0.0-beta.1.1.2",
    "babel": "npm:babel-core@5.8.35",
    "babel-runtime": "npm:babel-runtime@5.8.35",
    "bootstrap": "github:twbs/bootstrap@3.3.6",
    "core-js": "npm:core-js@2.1.3",
    "fetch": "github:github/fetch@0.10.1",
    "font-awesome": "npm:font-awesome@4.5.0",
    "highlight.js": "npm:highlight.js@9.2.0",
    "isagalaev/highlight.js": "github:isagalaev/highlight.js@9.2.0",
    "text": "github:systemjs/plugin-text@0.0.3",
    "github:jspm/nodelibs-assert@0.1.0": {
      "assert": "npm:assert@1.3.0"
    },
    "github:jspm/nodelibs-buffer@0.1.0": {
      "buffer": "npm:buffer@3.6.0"
    },
    "github:jspm/nodelibs-path@0.1.0": {
      "path-browserify": "npm:path-browserify@0.0.0"
    },
    "github:jspm/nodelibs-process@0.1.2": {
      "process": "npm:process@0.11.2"
    },
    "github:jspm/nodelibs-util@0.1.0": {
      "util": "npm:util@0.10.3"
    },
    "github:twbs/bootstrap@3.3.6": {
      "jquery": "github:components/jquery@2.2.1"
    },
    "npm:assert@1.3.0": {
      "util": "npm:util@0.10.3"
    },
    "npm:aurelia-animator-css@1.0.0-beta.1.1.2": {
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.1.5",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.1.1",
      "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1.1.2"
    },
    "npm:aurelia-binding@1.0.0-beta.1.2.1": {
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.1.5",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.1.1",
      "aurelia-task-queue": "npm:aurelia-task-queue@1.0.0-beta.1.1.1"
    },
    "npm:aurelia-bootstrapper@1.0.0-beta.1.1.4": {
      "aurelia-event-aggregator": "npm:aurelia-event-aggregator@1.0.0-beta.1.1.1",
      "aurelia-framework": "npm:aurelia-framework@1.0.0-beta.1.1.4",
      "aurelia-history": "npm:aurelia-history@1.0.0-beta.1.1.1",
      "aurelia-history-browser": "npm:aurelia-history-browser@1.0.0-beta.1.1.4",
      "aurelia-loader-default": "npm:aurelia-loader-default@1.0.0-beta.1.1.3",
      "aurelia-logging-console": "npm:aurelia-logging-console@1.0.0-beta.1.1.4",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.1.1",
      "aurelia-pal-browser": "npm:aurelia-pal-browser@1.0.0-beta.1.1.4",
      "aurelia-polyfills": "npm:aurelia-polyfills@1.0.0-beta.1.0.0",
      "aurelia-router": "npm:aurelia-router@1.0.0-beta.1.1.2",
      "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1.1.2",
      "aurelia-templating-binding": "npm:aurelia-templating-binding@1.0.0-beta.1.1.2",
      "aurelia-templating-resources": "npm:aurelia-templating-resources@1.0.0-beta.1.1.2",
      "aurelia-templating-router": "npm:aurelia-templating-router@1.0.0-beta.1.1.2"
    },
    "npm:aurelia-dependency-injection@1.0.0-beta.1.1.4": {
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.1.2",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.1.5",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.1.1"
    },
    "npm:aurelia-event-aggregator@1.0.0-beta.1.1.1": {
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.1.2"
    },
    "npm:aurelia-framework@1.0.0-beta.1.1.4": {
      "aurelia-binding": "npm:aurelia-binding@1.0.0-beta.1.2.1",
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.1.1.4",
      "aurelia-loader": "npm:aurelia-loader@1.0.0-beta.1.1.1",
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.1.2",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.1.5",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.1.1",
      "aurelia-path": "npm:aurelia-path@1.0.0-beta.1.1.1",
      "aurelia-task-queue": "npm:aurelia-task-queue@1.0.0-beta.1.1.1",
      "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1.1.2"
    },
    "npm:aurelia-history-browser@1.0.0-beta.1.1.4": {
      "aurelia-history": "npm:aurelia-history@1.0.0-beta.1.1.1",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.1.1"
    },
    "npm:aurelia-loader-default@1.0.0-beta.1.1.3": {
      "aurelia-loader": "npm:aurelia-loader@1.0.0-beta.1.1.1",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.1.5",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.1.1"
    },
    "npm:aurelia-loader@1.0.0-beta.1.1.1": {
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.1.5",
      "aurelia-path": "npm:aurelia-path@1.0.0-beta.1.1.1"
    },
    "npm:aurelia-logging-console@1.0.0-beta.1.1.4": {
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.1.2",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.1.1"
    },
    "npm:aurelia-metadata@1.0.0-beta.1.1.5": {
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.1.1"
    },
    "npm:aurelia-pal-browser@1.0.0-beta.1.1.4": {
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.1.1"
    },
    "npm:aurelia-polyfills@1.0.0-beta.1.0.0": {
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.1.1"
    },
    "npm:aurelia-route-recognizer@1.0.0-beta.1.1.2": {
      "aurelia-path": "npm:aurelia-path@1.0.0-beta.1.1.1"
    },
    "npm:aurelia-router@1.0.0-beta.1.1.2": {
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.1.1.4",
      "aurelia-event-aggregator": "npm:aurelia-event-aggregator@1.0.0-beta.1.1.1",
      "aurelia-history": "npm:aurelia-history@1.0.0-beta.1.1.1",
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.1.2",
      "aurelia-path": "npm:aurelia-path@1.0.0-beta.1.1.1",
      "aurelia-route-recognizer": "npm:aurelia-route-recognizer@1.0.0-beta.1.1.2"
    },
    "npm:aurelia-task-queue@1.0.0-beta.1.1.1": {
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.1.1"
    },
    "npm:aurelia-templating-binding@1.0.0-beta.1.1.2": {
      "aurelia-binding": "npm:aurelia-binding@1.0.0-beta.1.2.1",
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.1.2",
      "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1.1.2"
    },
    "npm:aurelia-templating-resources@1.0.0-beta.1.1.2": {
      "aurelia-binding": "npm:aurelia-binding@1.0.0-beta.1.2.1",
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.1.1.4",
      "aurelia-loader": "npm:aurelia-loader@1.0.0-beta.1.1.1",
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.1.2",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.1.1",
      "aurelia-path": "npm:aurelia-path@1.0.0-beta.1.1.1",
      "aurelia-task-queue": "npm:aurelia-task-queue@1.0.0-beta.1.1.1",
      "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1.1.2"
    },
    "npm:aurelia-templating-router@1.0.0-beta.1.1.2": {
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.1.1.4",
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.1.2",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.1.5",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.1.1",
      "aurelia-path": "npm:aurelia-path@1.0.0-beta.1.1.1",
      "aurelia-router": "npm:aurelia-router@1.0.0-beta.1.1.2",
      "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1.1.2"
    },
    "npm:aurelia-templating@1.0.0-beta.1.1.2": {
      "aurelia-binding": "npm:aurelia-binding@1.0.0-beta.1.2.1",
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.1.1.4",
      "aurelia-loader": "npm:aurelia-loader@1.0.0-beta.1.1.1",
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.1.2",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.1.5",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.1.1",
      "aurelia-path": "npm:aurelia-path@1.0.0-beta.1.1.1",
      "aurelia-task-queue": "npm:aurelia-task-queue@1.0.0-beta.1.1.1"
    },
    "npm:babel-runtime@5.8.35": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:buffer@3.6.0": {
      "base64-js": "npm:base64-js@0.0.8",
      "child_process": "github:jspm/nodelibs-child_process@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "ieee754": "npm:ieee754@1.1.6",
      "isarray": "npm:isarray@1.0.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:core-js@2.1.3": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:font-awesome@4.5.0": {
      "css": "github:systemjs/plugin-css@0.1.20"
    },
    "npm:highlight.js@9.2.0": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:inherits@2.0.1": {
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:path-browserify@0.0.0": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:process@0.11.2": {
      "assert": "github:jspm/nodelibs-assert@0.1.0"
    },
    "npm:util@0.10.3": {
      "inherits": "npm:inherits@2.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2"
    }
  },
  bundles: {
    "app-build-eddd65d665.js": [
      "app.html!github:systemjs/plugin-text@0.0.3.js",
      "app.js",
      "blur-image.js",
      "code-template.html!github:systemjs/plugin-text@0.0.3.js",
      "debugging.html!github:systemjs/plugin-text@0.0.3.js",
      "formating.html!github:systemjs/plugin-text@0.0.3.js",
      "formating.js",
      "main.js",
      "naming.html!github:systemjs/plugin-text@0.0.3.js",
      "naming.js",
      "nav-bar.html!github:systemjs/plugin-text@0.0.3.js",
      "overview.html!github:systemjs/plugin-text@0.0.3.js",
      "overview.js",
      "recommend.html!github:systemjs/plugin-text@0.0.3.js",
      "recommend.js",
      "scripts.js",
      "style.html!github:systemjs/plugin-text@0.0.3.js",
      "style.js"
    ],
    "aurelia-9860090fae.js": [
      "github:components/jquery@2.2.1.js",
      "github:components/jquery@2.2.1/jquery.js",
      "github:jspm/nodelibs-buffer@0.1.0.js",
      "github:jspm/nodelibs-buffer@0.1.0/index.js",
      "github:jspm/nodelibs-process@0.1.2.js",
      "github:jspm/nodelibs-process@0.1.2/index.js",
      "github:systemjs/plugin-text@0.0.3.js",
      "github:systemjs/plugin-text@0.0.3/text.js",
      "github:twbs/bootstrap@3.3.6.js",
      "github:twbs/bootstrap@3.3.6/css/bootstrap.css!github:systemjs/plugin-text@0.0.3.js",
      "github:twbs/bootstrap@3.3.6/js/bootstrap.js",
      "npm:aurelia-animator-css@1.0.0-beta.1.1.2.js",
      "npm:aurelia-animator-css@1.0.0-beta.1.1.2/aurelia-animator-css.js",
      "npm:aurelia-binding@1.0.0-beta.1.2.1.js",
      "npm:aurelia-binding@1.0.0-beta.1.2.1/aurelia-binding.js",
      "npm:aurelia-bootstrapper@1.0.0-beta.1.1.4.js",
      "npm:aurelia-bootstrapper@1.0.0-beta.1.1.4/aurelia-bootstrapper.js",
      "npm:aurelia-dependency-injection@1.0.0-beta.1.1.4.js",
      "npm:aurelia-dependency-injection@1.0.0-beta.1.1.4/aurelia-dependency-injection.js",
      "npm:aurelia-event-aggregator@1.0.0-beta.1.1.1.js",
      "npm:aurelia-event-aggregator@1.0.0-beta.1.1.1/aurelia-event-aggregator.js",
      "npm:aurelia-fetch-client@1.0.0-beta.1.1.1.js",
      "npm:aurelia-fetch-client@1.0.0-beta.1.1.1/aurelia-fetch-client.js",
      "npm:aurelia-framework@1.0.0-beta.1.1.4.js",
      "npm:aurelia-framework@1.0.0-beta.1.1.4/aurelia-framework.js",
      "npm:aurelia-history-browser@1.0.0-beta.1.1.4.js",
      "npm:aurelia-history-browser@1.0.0-beta.1.1.4/aurelia-history-browser.js",
      "npm:aurelia-history@1.0.0-beta.1.1.1.js",
      "npm:aurelia-history@1.0.0-beta.1.1.1/aurelia-history.js",
      "npm:aurelia-loader-default@1.0.0-beta.1.1.3.js",
      "npm:aurelia-loader-default@1.0.0-beta.1.1.3/aurelia-loader-default.js",
      "npm:aurelia-loader@1.0.0-beta.1.1.1.js",
      "npm:aurelia-loader@1.0.0-beta.1.1.1/aurelia-loader.js",
      "npm:aurelia-logging-console@1.0.0-beta.1.1.4.js",
      "npm:aurelia-logging-console@1.0.0-beta.1.1.4/aurelia-logging-console.js",
      "npm:aurelia-logging@1.0.0-beta.1.1.2.js",
      "npm:aurelia-logging@1.0.0-beta.1.1.2/aurelia-logging.js",
      "npm:aurelia-metadata@1.0.0-beta.1.1.5.js",
      "npm:aurelia-metadata@1.0.0-beta.1.1.5/aurelia-metadata.js",
      "npm:aurelia-pal-browser@1.0.0-beta.1.1.4.js",
      "npm:aurelia-pal-browser@1.0.0-beta.1.1.4/aurelia-pal-browser.js",
      "npm:aurelia-pal@1.0.0-beta.1.1.1.js",
      "npm:aurelia-pal@1.0.0-beta.1.1.1/aurelia-pal.js",
      "npm:aurelia-path@1.0.0-beta.1.1.1.js",
      "npm:aurelia-path@1.0.0-beta.1.1.1/aurelia-path.js",
      "npm:aurelia-polyfills@1.0.0-beta.1.0.0.js",
      "npm:aurelia-polyfills@1.0.0-beta.1.0.0/aurelia-polyfills.js",
      "npm:aurelia-route-recognizer@1.0.0-beta.1.1.2.js",
      "npm:aurelia-route-recognizer@1.0.0-beta.1.1.2/aurelia-route-recognizer.js",
      "npm:aurelia-router@1.0.0-beta.1.1.2.js",
      "npm:aurelia-router@1.0.0-beta.1.1.2/aurelia-router.js",
      "npm:aurelia-task-queue@1.0.0-beta.1.1.1.js",
      "npm:aurelia-task-queue@1.0.0-beta.1.1.1/aurelia-task-queue.js",
      "npm:aurelia-templating-binding@1.0.0-beta.1.1.2.js",
      "npm:aurelia-templating-binding@1.0.0-beta.1.1.2/aurelia-templating-binding.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.2.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.2/analyze-view-factory.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.2/array-repeat-strategy.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.2/aurelia-templating-resources.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.2/binding-mode-behaviors.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.2/binding-signaler.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.2/compile-spy.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.2/compose.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.2/css-resource.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.2/debounce-binding-behavior.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.2/dynamic-element.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.2/focus.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.2/hide.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.2/html-sanitizer.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.2/if.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.2/map-repeat-strategy.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.2/null-repeat-strategy.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.2/number-repeat-strategy.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.2/repeat-strategy-locator.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.2/repeat-utilities.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.2/repeat.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.2/replaceable.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.2/sanitize-html.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.2/set-repeat-strategy.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.2/show.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.2/signal-binding-behavior.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.2/throttle-binding-behavior.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.2/update-trigger-binding-behavior.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.2/view-spy.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.2/with.js",
      "npm:aurelia-templating-router@1.0.0-beta.1.1.2.js",
      "npm:aurelia-templating-router@1.0.0-beta.1.1.2/aurelia-templating-router.js",
      "npm:aurelia-templating-router@1.0.0-beta.1.1.2/route-href.js",
      "npm:aurelia-templating-router@1.0.0-beta.1.1.2/route-loader.js",
      "npm:aurelia-templating-router@1.0.0-beta.1.1.2/router-view.js",
      "npm:aurelia-templating@1.0.0-beta.1.1.2.js",
      "npm:aurelia-templating@1.0.0-beta.1.1.2/aurelia-templating.js",
      "npm:base64-js@0.0.8.js",
      "npm:base64-js@0.0.8/lib/b64.js",
      "npm:buffer@3.6.0.js",
      "npm:buffer@3.6.0/index.js",
      "npm:highlight.js@9.2.0.js",
      "npm:highlight.js@9.2.0/lib/highlight.js",
      "npm:highlight.js@9.2.0/lib/index.js",
      "npm:highlight.js@9.2.0/lib/languages/1c.js",
      "npm:highlight.js@9.2.0/lib/languages/accesslog.js",
      "npm:highlight.js@9.2.0/lib/languages/actionscript.js",
      "npm:highlight.js@9.2.0/lib/languages/apache.js",
      "npm:highlight.js@9.2.0/lib/languages/applescript.js",
      "npm:highlight.js@9.2.0/lib/languages/arduino.js",
      "npm:highlight.js@9.2.0/lib/languages/armasm.js",
      "npm:highlight.js@9.2.0/lib/languages/asciidoc.js",
      "npm:highlight.js@9.2.0/lib/languages/aspectj.js",
      "npm:highlight.js@9.2.0/lib/languages/autohotkey.js",
      "npm:highlight.js@9.2.0/lib/languages/autoit.js",
      "npm:highlight.js@9.2.0/lib/languages/avrasm.js",
      "npm:highlight.js@9.2.0/lib/languages/axapta.js",
      "npm:highlight.js@9.2.0/lib/languages/bash.js",
      "npm:highlight.js@9.2.0/lib/languages/basic.js",
      "npm:highlight.js@9.2.0/lib/languages/brainfuck.js",
      "npm:highlight.js@9.2.0/lib/languages/cal.js",
      "npm:highlight.js@9.2.0/lib/languages/capnproto.js",
      "npm:highlight.js@9.2.0/lib/languages/ceylon.js",
      "npm:highlight.js@9.2.0/lib/languages/clojure-repl.js",
      "npm:highlight.js@9.2.0/lib/languages/clojure.js",
      "npm:highlight.js@9.2.0/lib/languages/cmake.js",
      "npm:highlight.js@9.2.0/lib/languages/coffeescript.js",
      "npm:highlight.js@9.2.0/lib/languages/cos.js",
      "npm:highlight.js@9.2.0/lib/languages/cpp.js",
      "npm:highlight.js@9.2.0/lib/languages/crmsh.js",
      "npm:highlight.js@9.2.0/lib/languages/crystal.js",
      "npm:highlight.js@9.2.0/lib/languages/cs.js",
      "npm:highlight.js@9.2.0/lib/languages/csp.js",
      "npm:highlight.js@9.2.0/lib/languages/css.js",
      "npm:highlight.js@9.2.0/lib/languages/d.js",
      "npm:highlight.js@9.2.0/lib/languages/dart.js",
      "npm:highlight.js@9.2.0/lib/languages/delphi.js",
      "npm:highlight.js@9.2.0/lib/languages/diff.js",
      "npm:highlight.js@9.2.0/lib/languages/django.js",
      "npm:highlight.js@9.2.0/lib/languages/dns.js",
      "npm:highlight.js@9.2.0/lib/languages/dockerfile.js",
      "npm:highlight.js@9.2.0/lib/languages/dos.js",
      "npm:highlight.js@9.2.0/lib/languages/dts.js",
      "npm:highlight.js@9.2.0/lib/languages/dust.js",
      "npm:highlight.js@9.2.0/lib/languages/elixir.js",
      "npm:highlight.js@9.2.0/lib/languages/elm.js",
      "npm:highlight.js@9.2.0/lib/languages/erb.js",
      "npm:highlight.js@9.2.0/lib/languages/erlang-repl.js",
      "npm:highlight.js@9.2.0/lib/languages/erlang.js",
      "npm:highlight.js@9.2.0/lib/languages/fix.js",
      "npm:highlight.js@9.2.0/lib/languages/fortran.js",
      "npm:highlight.js@9.2.0/lib/languages/fsharp.js",
      "npm:highlight.js@9.2.0/lib/languages/gams.js",
      "npm:highlight.js@9.2.0/lib/languages/gauss.js",
      "npm:highlight.js@9.2.0/lib/languages/gcode.js",
      "npm:highlight.js@9.2.0/lib/languages/gherkin.js",
      "npm:highlight.js@9.2.0/lib/languages/glsl.js",
      "npm:highlight.js@9.2.0/lib/languages/go.js",
      "npm:highlight.js@9.2.0/lib/languages/golo.js",
      "npm:highlight.js@9.2.0/lib/languages/gradle.js",
      "npm:highlight.js@9.2.0/lib/languages/groovy.js",
      "npm:highlight.js@9.2.0/lib/languages/haml.js",
      "npm:highlight.js@9.2.0/lib/languages/handlebars.js",
      "npm:highlight.js@9.2.0/lib/languages/haskell.js",
      "npm:highlight.js@9.2.0/lib/languages/haxe.js",
      "npm:highlight.js@9.2.0/lib/languages/hsp.js",
      "npm:highlight.js@9.2.0/lib/languages/htmlbars.js",
      "npm:highlight.js@9.2.0/lib/languages/http.js",
      "npm:highlight.js@9.2.0/lib/languages/inform7.js",
      "npm:highlight.js@9.2.0/lib/languages/ini.js",
      "npm:highlight.js@9.2.0/lib/languages/irpf90.js",
      "npm:highlight.js@9.2.0/lib/languages/java.js",
      "npm:highlight.js@9.2.0/lib/languages/javascript.js",
      "npm:highlight.js@9.2.0/lib/languages/json.js",
      "npm:highlight.js@9.2.0/lib/languages/julia.js",
      "npm:highlight.js@9.2.0/lib/languages/kotlin.js",
      "npm:highlight.js@9.2.0/lib/languages/lasso.js",
      "npm:highlight.js@9.2.0/lib/languages/less.js",
      "npm:highlight.js@9.2.0/lib/languages/lisp.js",
      "npm:highlight.js@9.2.0/lib/languages/livecodeserver.js",
      "npm:highlight.js@9.2.0/lib/languages/livescript.js",
      "npm:highlight.js@9.2.0/lib/languages/lua.js",
      "npm:highlight.js@9.2.0/lib/languages/makefile.js",
      "npm:highlight.js@9.2.0/lib/languages/markdown.js",
      "npm:highlight.js@9.2.0/lib/languages/mathematica.js",
      "npm:highlight.js@9.2.0/lib/languages/matlab.js",
      "npm:highlight.js@9.2.0/lib/languages/maxima.js",
      "npm:highlight.js@9.2.0/lib/languages/mel.js",
      "npm:highlight.js@9.2.0/lib/languages/mercury.js",
      "npm:highlight.js@9.2.0/lib/languages/mipsasm.js",
      "npm:highlight.js@9.2.0/lib/languages/mizar.js",
      "npm:highlight.js@9.2.0/lib/languages/mojolicious.js",
      "npm:highlight.js@9.2.0/lib/languages/monkey.js",
      "npm:highlight.js@9.2.0/lib/languages/nginx.js",
      "npm:highlight.js@9.2.0/lib/languages/nimrod.js",
      "npm:highlight.js@9.2.0/lib/languages/nix.js",
      "npm:highlight.js@9.2.0/lib/languages/nsis.js",
      "npm:highlight.js@9.2.0/lib/languages/objectivec.js",
      "npm:highlight.js@9.2.0/lib/languages/ocaml.js",
      "npm:highlight.js@9.2.0/lib/languages/openscad.js",
      "npm:highlight.js@9.2.0/lib/languages/oxygene.js",
      "npm:highlight.js@9.2.0/lib/languages/parser3.js",
      "npm:highlight.js@9.2.0/lib/languages/perl.js",
      "npm:highlight.js@9.2.0/lib/languages/pf.js",
      "npm:highlight.js@9.2.0/lib/languages/php.js",
      "npm:highlight.js@9.2.0/lib/languages/powershell.js",
      "npm:highlight.js@9.2.0/lib/languages/processing.js",
      "npm:highlight.js@9.2.0/lib/languages/profile.js",
      "npm:highlight.js@9.2.0/lib/languages/prolog.js",
      "npm:highlight.js@9.2.0/lib/languages/protobuf.js",
      "npm:highlight.js@9.2.0/lib/languages/puppet.js",
      "npm:highlight.js@9.2.0/lib/languages/python.js",
      "npm:highlight.js@9.2.0/lib/languages/q.js",
      "npm:highlight.js@9.2.0/lib/languages/qml.js",
      "npm:highlight.js@9.2.0/lib/languages/r.js",
      "npm:highlight.js@9.2.0/lib/languages/rib.js",
      "npm:highlight.js@9.2.0/lib/languages/roboconf.js",
      "npm:highlight.js@9.2.0/lib/languages/rsl.js",
      "npm:highlight.js@9.2.0/lib/languages/ruby.js",
      "npm:highlight.js@9.2.0/lib/languages/ruleslanguage.js",
      "npm:highlight.js@9.2.0/lib/languages/rust.js",
      "npm:highlight.js@9.2.0/lib/languages/scala.js",
      "npm:highlight.js@9.2.0/lib/languages/scheme.js",
      "npm:highlight.js@9.2.0/lib/languages/scilab.js",
      "npm:highlight.js@9.2.0/lib/languages/scss.js",
      "npm:highlight.js@9.2.0/lib/languages/smali.js",
      "npm:highlight.js@9.2.0/lib/languages/smalltalk.js",
      "npm:highlight.js@9.2.0/lib/languages/sml.js",
      "npm:highlight.js@9.2.0/lib/languages/sqf.js",
      "npm:highlight.js@9.2.0/lib/languages/sql.js",
      "npm:highlight.js@9.2.0/lib/languages/stan.js",
      "npm:highlight.js@9.2.0/lib/languages/stata.js",
      "npm:highlight.js@9.2.0/lib/languages/step21.js",
      "npm:highlight.js@9.2.0/lib/languages/stylus.js",
      "npm:highlight.js@9.2.0/lib/languages/swift.js",
      "npm:highlight.js@9.2.0/lib/languages/tcl.js",
      "npm:highlight.js@9.2.0/lib/languages/tex.js",
      "npm:highlight.js@9.2.0/lib/languages/thrift.js",
      "npm:highlight.js@9.2.0/lib/languages/tp.js",
      "npm:highlight.js@9.2.0/lib/languages/twig.js",
      "npm:highlight.js@9.2.0/lib/languages/typescript.js",
      "npm:highlight.js@9.2.0/lib/languages/vala.js",
      "npm:highlight.js@9.2.0/lib/languages/vbnet.js",
      "npm:highlight.js@9.2.0/lib/languages/vbscript-html.js",
      "npm:highlight.js@9.2.0/lib/languages/vbscript.js",
      "npm:highlight.js@9.2.0/lib/languages/verilog.js",
      "npm:highlight.js@9.2.0/lib/languages/vhdl.js",
      "npm:highlight.js@9.2.0/lib/languages/vim.js",
      "npm:highlight.js@9.2.0/lib/languages/x86asm.js",
      "npm:highlight.js@9.2.0/lib/languages/xl.js",
      "npm:highlight.js@9.2.0/lib/languages/xml.js",
      "npm:highlight.js@9.2.0/lib/languages/xquery.js",
      "npm:highlight.js@9.2.0/lib/languages/yaml.js",
      "npm:highlight.js@9.2.0/lib/languages/zephir.js",
      "npm:ieee754@1.1.6.js",
      "npm:ieee754@1.1.6/index.js",
      "npm:isarray@1.0.0.js",
      "npm:isarray@1.0.0/index.js",
      "npm:process@0.11.2.js",
      "npm:process@0.11.2/browser.js"
    ]
  },
  depCache: {
    "blur-image.js": [
      "aurelia-framework"
    ],
    "main.js": [
      "bootstrap"
    ],
    "naming.js": [
      "assets/abstract"
    ]
  }
});